# See more keys and their definitions at https://rust-lang.github.io/rustfmt
max_width            = 120
use_small_heuristics = "Max"


# Unstable Features `+Nightly`
group_imports       = "One"
imports_granularity = "Module"
unstable_features   = true
